name: reading_app
description: "A reading app with login and web content viewing"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.5
  http: ^1.1.0
  file_picker: ^10.3.3  # Use this stable version
  syncfusion_flutter_pdf: ^31.1.19
  path_provider: ^2.1.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true